name: CI - test, version & publish

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Node config 
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install deps
      run: npm install

    - name: Sync testing branch with main
      run: |
        git fetch origin main
        git checkout test
        git merge origin/main

    - name: Run tests
      run: npm run test